Feature/reddit
aracelicaes/micro_reddit pull request #1
Opened 2020-08-20 19:44 UTC by jessicafarias

We created 3 models which created User, Post and Comment classes inheriting from ApplicationRecord and then generating the ActiveRecord:: Migration[6.0] for each class.
We then added ActiveRecord validations :
- to verify the presence of the users in each post and comment
- to verify the presence of the email and username

2020-08-20 22:20 UTC, Dandush03 requested changes
# Status: :red_circle:  Require Changes :red_circle: 
## Great Work so Far
### There are some validation that are missing, please check my comment below
# Happy Coding :rocket: :computer:

2020-08-20 22:20 UTC, Dandush03 commented on app/models/comment.rb
> +  validates :post, presence: true
#### Missing Validation
- [ ] `body` - Should not be able to receive an empty value. Missing Validation

2020-08-20 22:20 UTC, Dandush03 commented on app/models/post.rb
> +  validates :user, presence: true
#### Missing Validation
- [ ] `title` - Should not be able to receive an empty value. Missing Validation
- [ ] `body` - Should not be able to receive an empty value. Missing Validation

2020-08-21 00:37 UTC, uryelah approved these changes
Hi **Jessica Farías Rosado & Ara Camarillo Estudillo**, I'm Sarah your reviewer for this PR 👩‍🚀 

You did an awesome job with the validations, specially the one for the emal!

Go forth and rock your next project!  👩‍🎤  🎸  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-21 02:38 UTC, merged